export const GET_NETFLIX_ORGINALS = 'GET_NETFLIX_ORGINALS';
export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES';
export const GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES';
export const GET_ACTION_MOVIES = 'GET_ACTION_MOVIES';
export const GET_COMEDY_MOVIES = 'GET_COMEDY_MOVIES';
export const GET_HORROR_MOVIES = 'GET_HORROR_MOVIES';
export const GET_ROMANCE_MOVIES = 'GET_ROMANCE_MOVIES';
export const GET_DOCUMENTARIES = 'GET_DOCUMENTARIES';

export const SET_MOVIE_DETAILS = 'SET_MOVIE_DETAILS';

export const GET_SEARCH_MOVIES = 'GET_SEARCH_MOVIES';